
@url=http://127.0.0.1:7777
@json=Content-Type: application/json




### 获取用户

post {{url}}/get_user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNmJiNTU4OTk0NDZkNWVkYmI5YzA1NSIsInVzZXIiOiJrZnJvb3QiLCJkZXBhcnRtZW50Ijoi5byA5Y-R6YOoIiwicG9zaXRpb24iOiLnu4_nkIYiLCJpYXQiOjE2NTE1NDc0NTJ9.72s5w3KGxAnEncCRmoJJtThxT5O4nN2FsoyG8sj0RGs
{{json}}
